### ISSUE TITLE
Trying to enter SSP after leaving a world freezes game

### ISSUE THREAD

**Issue by robaimes** [DNSTechpack/DNS12-MC1.12.2#9]
* **Type of issue?**
  * Bug
  
* **DNS Version?**
  * 12.0.0.0
  
* **Description?** 
  * Can't enter/create new world if previously left another world
  * Looks to be caused posssibly by WorldEdit or FAWE.

Log:
```
08/11/2017 22:52:09 PM] [Server thread/INFO]: Stopping server
[08/11/2017 22:52:09 PM] [Server thread/INFO]: Saving players
[08/11/2017 22:52:10 PM] [22:52:10] [Server thread/INFO]: **MINECRAFTUSERNAME** lost connection: Internal Exception: java.nio.channels.ClosedChannelException
[08/11/2017 22:52:10 PM] [Server thread/INFO]: **MINECRAFTUSERNAME** left the game
[08/11/2017 22:52:10 PM] [22:52:10] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@6076b4c9:
[08/11/2017 22:52:10 PM] com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting CONFIGURATION
[08/11/2017 22:52:10 PM] 	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:190) ~[PlatformManager.class:?]
[08/11/2017 22:52:10 PM] 	at com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:321) ~[PlatformManager.class:?]
[08/11/2017 22:52:10 PM] 	at com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:801) ~[WorldEdit.class:?]
[08/11/2017 22:52:10 PM] 	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:172) ~[SessionManager.class:?]
[08/11/2017 22:52:10 PM] 	at com.sk89q.worldedit.WorldEdit.getSession(WorldEdit.java:210) ~[WorldEdit.class:?]
[08/11/2017 22:52:10 PM] 	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:483) ~[FawePlayer.class:?]
[08/11/2017 22:52:10 PM] 	at com.boydti.fawe.object.FawePlayer.unregister(FawePlayer.java:559) ~[FawePlayer.class:?]
[08/11/2017 22:52:10 PM] 	at com.boydti.fawe.forge.ForgeMain.handleQuit(ForgeMain.java:66) ~[ForgeMain.class:?]
[08/11/2017 22:52:10 PM] 	at com.boydti.fawe.forge.ForgeMain.onPlayerQuit(ForgeMain.java:53) ~[ForgeMain.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1098_ForgeMain_onPlayerQuit_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
[08/11/2017 22:52:10 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578) [FMLCommonHandler.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387) [pl.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849) [pa.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:452) [gw.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:291) [pa$2.class:?]
[08/11/2017 22:52:10 PM] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1381) [MinecraftServer.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1393) [MinecraftServer.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:287) [pa.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1070) [pl.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:431) [MinecraftServer.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:463) [chd.class:?]
[08/11/2017 22:52:10 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:577) [MinecraftServer.class:?]
[08/11/2017 22:52:10 PM] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
```

**Comment by robaimes** [comment]
Looks to be caused by FAWE. Removing clientside stops issue.

**Comment by robaimes** [comment]
Caused by FAWE - Removed clientside, serverside only mod.
